# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_cro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='patrimonio',
        ),
        migrations.AlterField(
            model_name='rating',
            name='activo_corriente',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='activo_no_corriente',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fondos_propios',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='gastos_financieros',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='importe_neto_cifra_negocio',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='pasivo_corriente',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='pasivo_no_corriente',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='resultados_antes_impuestos',
            field=models.BigIntegerField(),
        ),
    ]
