# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('data_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('sector', models.CharField(max_length=255)),
                ('cnae', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
                ('hats_date', models.DateField()),
                ('hats_alert', models.CharField(max_length=30)),
                ('concursal', models.CharField(max_length=10)),
                ('recent_creation', models.CharField(max_length=10)),
                ('segment', models.CharField(max_length=128)),
                ('subsegment', models.CharField(max_length=128)),
                ('territorial', models.CharField(max_length=255)),
                ('regional', models.CharField(max_length=255)),
                ('centro_gestor', models.CharField(max_length=255)),
                ('oficina', models.IntegerField()),
            ],
        ),
    ]
