# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('data_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(max_length=255)),
                ('cnae', models.CharField(max_length=255)),
                ('cnae_2', models.CharField(blank=True, max_length=255, null=True)),
                ('cnae_num', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(max_length=255)),
                ('hats_date', models.DateField(blank=True, null=True)),
                ('hats_alert', models.CharField(max_length=30)),
                ('concursal', models.CharField(max_length=10)),
                ('recent_creation', models.CharField(max_length=10)),
                ('segment', models.CharField(max_length=128)),
                ('subsegment', models.CharField(max_length=128)),
                ('territorial', models.CharField(max_length=255)),
                ('regional', models.CharField(max_length=255)),
                ('centro_gestor', models.CharField(max_length=255)),
                ('oficina', models.IntegerField()),
                ('state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='_empresa_clients_+', to='empresas.Empresa')),
                ('oportunities', models.ManyToManyField(blank=True, related_name='_empresa_oportunities_+', to='empresas.Empresa')),
                ('providers', models.ManyToManyField(blank=True, related_name='_empresa_providers_+', to='empresas.Empresa')),
                ('recommended_clients', models.ManyToManyField(blank=True, related_name='_empresa_recommended_clients_+', to='empresas.Empresa')),
                ('recommended_providers', models.ManyToManyField(blank=True, related_name='_empresa_recommended_providers_+', to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EstadosFinancieros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(blank=True, max_length=16, null=True)),
                ('fecha_balance', models.DateField(blank=True, null=True)),
                ('ventas', models.FloatField(blank=True, null=True)),
                ('depreciaciones', models.FloatField(blank=True, null=True)),
                ('amortizaciones', models.FloatField(blank=True, null=True)),
                ('ebitda', models.FloatField(blank=True, null=True)),
                ('resultado_explotacion', models.FloatField(blank=True, null=True)),
                ('existencias', models.FloatField(blank=True, null=True)),
                ('deudores', models.FloatField(blank=True, null=True)),
                ('periodificaciones_ac', models.FloatField(blank=True, null=True)),
                ('provisiones_cp', models.FloatField(blank=True, null=True)),
                ('acreedores_comerciales', models.FloatField(blank=True, null=True)),
                ('periodificaciones_pc', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_financieros', to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_persona', models.IntegerField(blank=True, null=True)),
                ('tipo_producto', models.CharField(blank=True, max_length=5, null=True)),
                ('producto', models.CharField(blank=True, max_length=128, null=True)),
                ('desc_producto', models.CharField(blank=True, max_length=128, null=True)),
                ('id_contrato', models.CharField(blank=True, max_length=32, null=True)),
                ('concedido', models.FloatField(blank=True, null=True)),
                ('dispuesto', models.FloatField(blank=True, null=True)),
                ('impagado', models.FloatField(blank=True, null=True)),
                ('dias_impago', models.FloatField(blank=True, null=True)),
                ('cuotas_impagadas', models.FloatField(blank=True, null=True)),
                ('fecha_datos', models.DateField(blank=True, null=True)),
                ('fecha_formalizacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('concedido_inicial', models.FloatField(blank=True, null=True)),
                ('capital_pdte', models.FloatField(blank=True, null=True)),
                ('interes_revisado', models.FloatField(blank=True, null=True)),
                ('cuotas_total', models.FloatField(blank=True, null=True)),
                ('cuota_anual', models.FloatField(blank=True, null=True)),
                ('cuota', models.FloatField(blank=True, null=True)),
                ('garantia_hip', models.CharField(blank=True, max_length=2, null=True)),
                ('sit_contable', models.CharField(blank=True, max_length=32, null=True)),
                ('segmento_gestion', models.CharField(blank=True, max_length=128, null=True)),
                ('refinanciado', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('clientes_recomendados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_recomendados', to='empresas.Empresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='empresas.Empresa')),
            ],
            options={
                'ordering': ['-similarity'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedProviders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('clientes_recomendados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_recomendados', to='empresas.Empresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers_recommended', to='empresas.Empresa')),
            ],
            options={
                'ordering': ['-similarity'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=255)),
                ('operation_data', models.DateTimeField()),
                ('value_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('destination_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reference', to='empresas.Empresa')),
                ('origin_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='empresas.Empresa')),
            ],
        ),
    ]
