# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIRBE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirbe_concedido', models.IntegerField(blank=True, null=True)),
                ('cirbe_dispuesto', models.IntegerField(blank=True, null=True)),
                ('largo_plazo_concedido', models.IntegerField(blank=True, null=True)),
                ('largo_plazo_dispuesto', models.IntegerField(blank=True, null=True)),
                ('corto_plazo_concedido', models.IntegerField(blank=True, null=True)),
                ('corto_plazo_dispuesto', models.IntegerField(blank=True, null=True)),
                ('d_concedido', models.IntegerField(blank=True, null=True)),
                ('d_dispuesto', models.IntegerField(blank=True, null=True)),
                ('avales_concedido', models.IntegerField(blank=True, null=True)),
                ('avales_dispuesto', models.IntegerField(blank=True, null=True)),
                ('leasing_concedido', models.IntegerField(blank=True, null=True)),
                ('leasing_dispuesto', models.IntegerField(blank=True, null=True)),
                ('sr_concedido', models.IntegerField(blank=True, null=True)),
                ('sr_dispuesto', models.IntegerField(blank=True, null=True)),
                ('moroso', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirbe', to='empresas.Empresa')),
            ],
        ),
        migrations.AlterModelOptions(
            name='estadosfinancieros',
            options={'ordering': ['ejercicio']},
        ),
    ]
