# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20161124_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
    ]
