# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20161229_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirbe',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cirbe', to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.Empresa'),
        ),
    ]
