# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20161124_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='hats_date',
            field=models.DateField(null=True),
        ),
    ]
