# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20161124_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default='gila.doe@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
