# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_cirbe_corto_plazo_concedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirbe',
            name='corto_plazo_concedido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
