# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=255)),
                ('operation_data', models.DateTimeField()),
                ('value_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('destination_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reference', to='empresas.Empresa')),
                ('origin_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_reference', to='empresas.Empresa')),
            ],
        ),
    ]
