# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_cirbe_corto_plazo_concedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='own_client',
            field=models.CharField(default='S\xcd', max_length=16),
            preserve_default=False,
        ),
    ]
