# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Transfer',
        ),
    ]
