# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_auto_20161124_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('clientes_recomendados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_recomendados', to='empresas.Empresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='empresas.Empresa')),
            ],
        ),
    ]
