# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_recommendedclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosFinancieros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.DateField()),
                ('fecha_balance', models.DateField()),
                ('ventas', models.FloatField()),
                ('depreciaciones', models.FloatField()),
                ('amortizaciones', models.FloatField()),
                ('ebitda', models.FloatField()),
                ('resultado_explotacion', models.FloatField()),
                ('existencias', models.FloatField()),
                ('deudores', models.FloatField()),
                ('periodificaciones_ac', models.FloatField()),
                ('provisiones_cp', models.FloatField()),
                ('acreedores_comerciales', models.FloatField()),
                ('periodificaciones_pc', models.FloatField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_persona', models.IntegerField()),
                ('tipo_producto', models.CharField(max_length=5)),
                ('producto', models.CharField(max_length=128)),
                ('desc_producto', models.CharField(max_length=128)),
                ('id_contrato', models.CharField(max_length=32)),
                ('concedido', models.FloatField()),
                ('dispuesto', models.FloatField()),
                ('impagado', models.IntegerField()),
                ('cuotas_impagadas', models.IntegerField()),
                ('fecha_formalizacion', models.DateField()),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('concedido_inicial', models.FloatField()),
                ('capital_pdte', models.FloatField()),
                ('interes_revisado', models.FloatField()),
                ('cuotas_total', models.IntegerField()),
                ('cuota_anual', models.FloatField()),
                ('cuota', models.FloatField()),
                ('garantia_hip', models.CharField(max_length=2)),
                ('sit_contable', models.CharField(max_length=32)),
                ('refinanciado', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
        ),
    ]
