# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_estadosfinancieros_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosfinancieros',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadosfinancieros',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='acreedores_comerciales',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='amortizaciones',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='depreciaciones',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='deudores',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='ebitda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='ejercicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='existencias',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='fecha_balance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='periodificaciones_ac',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='periodificaciones_pc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='provisiones_cp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='resultado_explotacion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='ventas',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='capital_pdte',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='concedido',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='concedido_inicial',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuota',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuota_anual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuotas_impagadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuotas_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='desc_producto',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='dispuesto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_formalizacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='garantia_hip',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_contrato',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='impagado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='interes_revisado',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='numero_persona',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='sit_contable',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo_producto',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
