# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_auto_20161201_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedclients',
            options={'ordering': ['-similarity']},
        ),
        migrations.AddField(
            model_name='empresa',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='state_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_financieros', to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuotas_impagadas',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuotas_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='dias_impago',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='impagado',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='origin_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='empresas.Empresa'),
        ),
    ]
