# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_auto_20161202_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
