# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_empresa_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='_empresa_clients_+', to='empresas.Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnae_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnae_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='_empresa_providers_+', to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='hats_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='state_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='acreedores_comerciales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='amortizaciones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='depreciaciones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='deudores',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='ebitda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='ejercicio',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_financieros', to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='existencias',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='fecha_balance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='periodificaciones_ac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='periodificaciones_pc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='provisiones_cp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='resultado_explotacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadosfinancieros',
            name='ventas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='capital_pdte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='concedido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='concedido_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuota_anual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuotas_impagadas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cuotas_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='desc_producto',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='dias_impago',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='dispuesto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_datos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_formalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='garantia_hip',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_contrato',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='impagado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='interes_revisado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='numero_persona',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='segmento_gestion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='sit_contable',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedclients',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='empresas.Empresa'),
        ),
    ]
