# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_auto_20161204_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='oportunities',
            field=models.ManyToManyField(blank=True, related_name='_empresa_oportunities_+', to='empresas.Empresa'),
        ),
    ]
