# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_empresa_oportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='recommended_clients',
            field=models.ManyToManyField(blank=True, related_name='_empresa_recommended_clients_+', to='empresas.Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='recommended_providers',
            field=models.ManyToManyField(blank=True, related_name='_empresa_recommended_providers_+', to='empresas.Empresa'),
        ),
    ]
