# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_auto_20161204_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contact_person',
            field=models.CharField(default='Hola', max_length=255),
            preserve_default=False,
        ),
    ]
